
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hp
 */
public class MyContactsForm extends javax.swing.JFrame {

    String imagePth = null;
    public static int currentUserId;
    
    int pos = 0;

    public MyContactsForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        populateJtable();

        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.YELLOW);
        jTable1.setSelectionBackground(Color.lightGray);

        JTableHeader th = jTable1.getTableHeader();
        th.setForeground(Color.BLUE);

        th.setFont(new Font("Montserrat Black", Font.BOLD, 12));
        System.out.println(currentUserId + "From Contact");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelUserPic = new javax.swing.JLabel();
        jLabelUsername = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxRole = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabelContactPic = new javax.swing.JLabel();
        jButtonBrowseImage = new javax.swing.JButton();
        jButtonDeleteContact = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddContact = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jButtonEditContact = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(46, 204, 113));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(436, 59));
        jPanel1.setLayout(null);

        jLabelMin.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("_");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelMin);
        jLabelMin.setBounds(920, 10, 20, 32);

        jLabel3.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("HR Management system");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 10, 320, 32);

        jLabelClose.setFont(new java.awt.Font("Montserrat Black", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose);
        jLabelClose.setBounds(950, 20, 16, 32);

        jLabelUserPic.setBackground(new java.awt.Color(255, 255, 0));
        jLabelUserPic.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabelUserPic.setOpaque(true);
        jPanel1.add(jLabelUserPic);
        jLabelUserPic.setBounds(0, 0, 70, 60);

        jLabelUsername.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Username");
        jPanel1.add(jLabelUsername);
        jLabelUsername.setBounds(80, 20, 90, 30);

        jPanel2.setBackground(new java.awt.Color(236, 236, 236));
        jPanel2.setToolTipText("");
        jPanel2.setMinimumSize(new java.awt.Dimension(436, 320));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 108, 179));
        jLabel4.setText("Role:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 200, 110, 50);

        jLabel5.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 108, 179));
        jLabel5.setText("ID:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 0, 110, 50);

        jTextFieldId.setEditable(false);
        jTextFieldId.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldId.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jTextFieldId.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldId);
        jTextFieldId.setBounds(120, 10, 250, 30);

        jLabel6.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 108, 179));
        jLabel6.setText("Last Name:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 80, 110, 50);

        jTextFieldLname.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldLname.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jTextFieldLname.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLname);
        jTextFieldLname.setBounds(120, 90, 250, 30);

        jLabel7.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 108, 179));
        jLabel7.setText("Email:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 160, 110, 50);

        jTextFieldEmail.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldEmail.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(120, 170, 250, 30);

        jLabel8.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(68, 108, 179));
        jLabel8.setText("Phone:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 120, 110, 50);

        jTextFieldPhone.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldPhone.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jTextFieldPhone.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPhone);
        jTextFieldPhone.setBounds(120, 130, 250, 30);

        jLabel9.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(68, 108, 179));
        jLabel9.setText("Address:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(410, 120, 90, 50);

        jComboBoxRole.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jComboBoxRole.setForeground(new java.awt.Color(68, 108, 179));
        jComboBoxRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctor", "Receptionist", "Patient" }));
        jPanel2.add(jComboBoxRole);
        jComboBoxRole.setBounds(120, 210, 250, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(390, 20, 20, 210);

        jLabel10.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 108, 179));
        jLabel10.setText("Profile pic:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(400, 20, 110, 50);

        jLabelContactPic.setBackground(new java.awt.Color(228, 241, 254));
        jLabelContactPic.setOpaque(true);
        jPanel2.add(jLabelContactPic);
        jLabelContactPic.setBounds(510, 30, 150, 100);

        jButtonBrowseImage.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBrowseImage.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jButtonBrowseImage.setText("Browse");
        jButtonBrowseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseImageActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonBrowseImage);
        jButtonBrowseImage.setBounds(680, 80, 75, 25);

        jButtonDeleteContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonDeleteContact.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jButtonDeleteContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDeleteContact.setText("Delete");
        jButtonDeleteContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeleteContact);
        jButtonDeleteContact.setBounds(513, 220, 90, 27);

        jTextAreaAddress.setBackground(new java.awt.Color(228, 241, 254));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jTextAreaAddress.setForeground(new java.awt.Color(68, 108, 179));
        jTextAreaAddress.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddress);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(510, 140, 250, 70);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(0, 280, 980, 250);

        jButtonAddContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonAddContact.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jButtonAddContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAddContact.setText("Add");
        jButtonAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddContact);
        jButtonAddContact.setBounds(700, 220, 61, 27);

        jLabel11.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(68, 108, 179));
        jLabel11.setText("First Name:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 40, 110, 50);

        jTextFieldFname.setBackground(new java.awt.Color(228, 241, 254));
        jTextFieldFname.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jTextFieldFname.setForeground(new java.awt.Color(68, 108, 179));
        jTextFieldFname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldFname);
        jTextFieldFname.setBounds(120, 50, 250, 30);

        jButtonEditContact.setBackground(new java.awt.Color(30, 139, 195));
        jButtonEditContact.setFont(new java.awt.Font("Montserrat Black", 1, 14)); // NOI18N
        jButtonEditContact.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditContact.setText("Edit");
        jButtonEditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditContact);
        jButtonEditContact.setBounds(620, 220, 59, 27);

        jButtonLast.setBackground(new java.awt.Color(255, 255, 255));
        jButtonLast.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jButtonLast.setText(">>");
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLast);
        jButtonLast.setBounds(340, 250, 47, 25);

        jButtonFirst.setBackground(new java.awt.Color(255, 255, 255));
        jButtonFirst.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jButtonFirst.setText("<<");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonFirst);
        jButtonFirst.setBounds(30, 250, 47, 25);

        jButtonPrevious.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPrevious.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jButtonPrevious.setText("<");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPrevious);
        jButtonPrevious.setBounds(130, 250, 39, 25);

        jButtonNext.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNext.setFont(new java.awt.Font("Montserrat Black", 1, 12)); // NOI18N
        jButtonNext.setText(">");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNext);
        jButtonNext.setBounds(230, 250, 39, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void populateJtable() {

        contactQuery cq = new contactQuery();
        ArrayList<contact> ctList = cq.contactList(currentUserId);

        String[] colNames = {"Id", "First Name", "Last Name", "Role", "Phone", "Email", "Address", "Image"};
        Object[][] rows = new Object[ctList.size()][8];

        for (int i = 0; i < ctList.size(); i++) {
            rows[i][0] = ctList.get(i).getCid();
            rows[i][1] = ctList.get(i).getFname();
            rows[i][2] = ctList.get(i).getLname();
            rows[i][3] = ctList.get(i).getRole();
            rows[i][4] = ctList.get(i).getPhone();
            rows[i][5] = ctList.get(i).getEmail();
            rows[i][6] = ctList.get(i).getAddress();

            ImageIcon pic = new ImageIcon(new ImageIcon(ctList.get(i).getPic())
                    .getImage().
                    getScaledInstance(120, 80, Image.SCALE_SMOOTH));

            rows[i][7] = pic;
        }
        MyModel mmd = new MyModel(rows, colNames);
        jTable1.setModel(mmd);
        jTable1.setRowHeight(80);
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(120);
    }

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jTextFieldLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLnameActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneActionPerformed

    private void jButtonBrowseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseImageActionPerformed

        Myfunc mf = new Myfunc();
        imagePth = mf.browseImage(jLabelContactPic);
        System.out.println(imagePth);

    }//GEN-LAST:event_jButtonBrowseImageActionPerformed

    private void jButtonDeleteContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteContactActionPerformed

        //the user has to select a contact to delete
        if (!jTextFieldId.getText().equals("")) {
            int id = Integer.valueOf(jTextFieldId.getText());
            contactQuery cq = new contactQuery();
            cq.deleteContact(id);
            refreshJtable();
            clearFields();
        } else{
            JOptionPane.showMessageDialog(null, "Select a contact from the table to delete");
        }

    }//GEN-LAST:event_jButtonDeleteContactActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        // display selected row data 
        // get selected row index
        int rowIndex = jTable1.getSelectedRow();
        jTextFieldFname.setText(jTable1.getValueAt(rowIndex, 1).toString());
        jTextFieldLname.setText(jTable1.getValueAt(rowIndex, 2).toString());

        //role phone email address pic
        jComboBoxRole.setSelectedItem(jTable1.getValueAt(rowIndex, 3));
        jTextFieldPhone.setText(jTable1.getValueAt(rowIndex, 4).toString());
        jTextFieldEmail.setText(jTable1.getValueAt(rowIndex, 5).toString());
        jTextFieldId.setText(jTable1.getValueAt(rowIndex, 0).toString());
        jTextAreaAddress.setText(jTable1.getValueAt(rowIndex, 6).toString());

        Image pic = ((ImageIcon) jTable1.getValueAt(rowIndex, 7)).getImage().getScaledInstance(jLabelContactPic.getWidth(), jLabelContactPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);

        jLabelContactPic.setIcon(img);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContactActionPerformed

        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldPhone.getText();
        String address = jTextAreaAddress.getText();
        String email = jTextFieldEmail.getText();
        String role = jComboBoxRole.getSelectedItem().toString();

        //checking if all the fields are empty
        //here we only check if the user has an image
        //using ImagePth
        byte[] img = null;

        if (imagePth != null) {

            try {

                Path pth = Paths.get(imagePth);
                img = Files.readAllBytes(pth);
                contact c = new contact(null, fname, lname, role, phone, email, address, img, currentUserId);
                contactQuery cq = new contactQuery();
                cq.insertContact(c);
                refreshJtable();
                clearFields();

            } catch (IOException ex) {
                Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "You have to select a profile picture!");
        }


    }//GEN-LAST:event_jButtonAddContactActionPerformed

    private void jTextFieldFnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFnameActionPerformed

    public void refreshJtable() {
        jTable1.setModel(new DefaultTableModel());
        populateJtable();
    }

    public void clearFields() {
        jTextFieldId.setText("");
        jTextFieldFname.setText("");
        jTextFieldLname.setText("");
        jTextFieldPhone.setText("");
        jTextAreaAddress.setText("");
        jTextFieldEmail.setText("");
        jComboBoxRole.setSelectedIndex(0);
        jLabelContactPic.setIcon(null);
        //set imagePth to null to prevent the user to add unwanted duplacate images
        imagePth = null;
    }

    private void showData(int index)
    {
        jTextFieldFname.setText(jTable1.getValueAt(index, 1).toString());
        jTextFieldLname.setText(jTable1.getValueAt(index, 2).toString());

        //role phone email address pic
        jComboBoxRole.setSelectedItem(jTable1.getValueAt(index, 3));
        jTextFieldPhone.setText(jTable1.getValueAt(index, 4).toString());
        jTextFieldEmail.setText(jTable1.getValueAt(index, 5).toString());
        jTextFieldId.setText(jTable1.getValueAt(index, 0).toString());
        jTextAreaAddress.setText(jTable1.getValueAt(index, 6).toString());

        Image pic = ((ImageIcon) jTable1.getValueAt(index, 7)).getImage().getScaledInstance(jLabelContactPic.getWidth(), jLabelContactPic.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img = new ImageIcon(pic);

        jLabelContactPic.setIcon(img);
    }
    
    private void jButtonEditContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditContactActionPerformed
//the user has to select a contact to edit       
      if(!jTextFieldId.getText().equals(""))
      {
       
        int id = Integer.valueOf(jTextFieldId.getText());
        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String phone = jTextFieldPhone.getText();
        String address = jTextAreaAddress.getText();
        String email = jTextFieldEmail.getText();
        String role = jComboBoxRole.getSelectedItem().toString();

        //if the user wants to update the data and the image
        if (imagePth != null) {
            byte[] img = null;
            try {
                Path pth = Paths.get(imagePth);
                img = Files.readAllBytes(pth);

                contact c = new contact(id, fname, lname, role, phone, email, address, img, currentUserId);
                contactQuery cq = new contactQuery();
                cq.updateContact(c, true);
                refreshJtable();
                clearFields();
            } catch (IOException ex) {
                Logger.getLogger(MyContactsForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            contact c = new contact(id, fname, lname, role, phone, email, address, null, currentUserId);
            contactQuery cq = new contactQuery();
            cq.updateContact(c, false);
            refreshJtable();
            clearFields();
        }
      }else{
          JOptionPane.showMessageDialog(null, "Select a contact from the table to edit");
      }
      
    }//GEN-LAST:event_jButtonEditContactActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
        pos = jTable1.getRowCount()-1; 
        showData(pos);
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        pos = 0;
        showData(pos);
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        pos--;
        showData(pos);
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        pos++;
        showData(pos);
    }//GEN-LAST:event_jButtonNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyContactsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyContactsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddContact;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JButton jButtonDeleteContact;
    private javax.swing.JButton jButtonEditContact;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JComboBox<String> jComboBoxRole;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelContactPic;
    private javax.swing.JLabel jLabelMin;
    public javax.swing.JLabel jLabelUserPic;
    public javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldPhone;
    // End of variables declaration//GEN-END:variables
}
